import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="main-nav">
          <div className="nav-wrapper">
            <div className="logo-wrapper">
              <img src="assets/images/logo.svg" alt="" />
            </div>
            <div className="right-side">
              <div className="search-bar-wrapper">
                <img src="assets/images/search-icon.png" alt="" />
                <input type="text" placeholder="Search" name id />
              </div>
              <span className="notifi">
                <img src="assets/images/notifi.png" alt="" />
              </span>
              <a >
                <div className="profile-wrap">
                  <div className="profile-img">
                    <img src="assets/images/profile.jpg" alt="" />
                  </div>
                  <div className="profile-det">
                    <h5 className="name">
                      John Doe
                    </h5>
                    <p className="desig">CEO</p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </nav>
      </header>
      <div className="sec-wrapper pt-5 pb-5">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h2 className="main-title white">
                My Account
              </h2>
            </div>
          </div>
          <div className="row justify-content-center">
            <div className="col-12 mt-60">
              <div className="c_card">
                <div className="card-body" style={{padding: '0px'}}>
                  <div className="row ">
                    <div className="col-lg-6 col-md-6 col-12 col-sm-12 first-col text-center" style={{borderRight: '1px solid rgba(0, 0, 0, 0.20)'}}>
                      <div className="card-header d-flex justify-content-between align-items-center">
                        <div className="heading">
                          <h3 className="title-1">User Journey 1</h3>
                        </div>
                      </div>
                      <div className="profile-devide">
                        <div className="profile-wrapper">
                          <div className="prof-img">
                            <img src="assets/images/profile.jpg" alt="" />
                          </div>
                          <div className="prof-icons">
                            <a>
                              <i className="fas fa-pencil-alt" /></a>
                            <a >
                              <i className="fas fa-trash" /></a>
                          </div>
                        </div>
                        <div className="form-inputs">
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="text" name placeholder="First Name" id />
                            </div>
                          </div>
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="text" name placeholder="Last Name" id />
                            </div>
                          </div>
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="email" name placeholder="Email" id />
                            </div>
                          </div>
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="text" name placeholder="Company" id />
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="profile-devide" style={{borderBottom: '0px !important'}}>
                        <div className="profile-wrapper">
                        </div>
                        <div className="form-inputs">
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="text" name placeholder="Username" id />
                            </div>
                          </div>
                          <div className="input-group">
                            <div className="input-wrapper">
                              <input type="password" name placeholder="Password" id />
                            </div>
                          </div>
                          <div className="d-flex justify-content-end">
                            <a href="/editpassword" className="plan-cta">EDIT PASSWORD</a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6 col-md-6 col-12 sec-col col-sm-12">
                      <div className="card-header d-flex justify-content-between align-items-center">
                        <div className="heading">
                          <h3 className="title-1">Payment information</h3>
                        </div>
                      </div>
                      <div className="profile-devide no-grid" style={{borderBottom: '0px !important'}}>
                        <img src="assets/images/debit.jpg" style={{maxWidth: '300px'}} alt="" />
                        <br />
                        <div className="row " style={{marginTop: '20px'}}>
                          <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                            <div className="input-group">
                              <div className="input-wrapper" style={{marginBottom: '10px'}}>
                                <input type="text" name placeholder="John Doe" id />
                              </div>
                            </div>
                          </div>
                          <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                            <div className="input-group" style={{marginBottom: '10px'}}>
                              <div className="input-wrapper">
                                <input type="text" name placeholder="1234 1234 1234 1233" id />
                              </div>
                            </div>
                          </div>
                          <div className="col-12 d-flex justify-content-start" style={{marginTop: '15px'}}>
                            <a href="/editpayment" className="plan-cta">EDIT PAYMENT METHOD</a>
                          </div>
                        </div>
                      </div>
                      <div className="card-header d-flex justify-content-between align-items-center">
                        <div className="heading">
                          <h3 className="title-1">Subscription Detail</h3>
                        </div>
                      </div>
                      <div className="d-flex align-items-center" style={{marginTop: '25px', paddingBottom: '30px', paddingLeft: '20px'}}>
                        <a  className="plan-cta">No plan selected</a>
                        <a href="/subscription" className="cta " style={{marginLeft: '20px'}}>CHANGE PLAN</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
