import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="main-nav">
          <div className="nav-wrapper">
            <div className="logo-wrapper">
              <img src="assets/images/logo.svg" alt="" />
            </div>
            <div className="right-side">
              <div className="search-bar-wrapper">
                <img src="assets/images/search-icon.png" alt="" />
                <input type="text" placeholder="Search" name id />
              </div>
              <span className="notifi">
                <img src="assets/images/notifi.png" alt="" />
              </span>
              <a href>
                <div className="profile-wrap">
                  <div className="profile-img">
                    <img src="assets/images/profile.jpg" alt="" />
                  </div>
                  <div className="profile-det">
                    <h5 className="name">
                      John Doe
                    </h5>
                    <p className="desig">CEO</p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </nav>
      </header>
      <form id="contact" action="#">
        <div>
          <ul className="d-flex steps-wrap" style={{height: '8px'}}>
            <li className="active" />
            <li className="active" />
          </ul>
          <section>
            <div className="sec-wrapper">
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-12 mt-60">
                    <div className="c_card">
                      <div className="card-header">
                        <div className="heading">
                          <h3 className="title">Add Hypertarget to your HTML Website</h3>
                          <p className="sub">It’s the only time you’ll be asked to use code.</p>
                        </div>
                      </div>
                      <div className="card-body">
                        <a href="#" className="cta animate__animated animate__animated animate__flipInX">COPY CODE</a>
                        <p className="theme-p animate__animated animate__fadeInLeft">
                          Copy and paste the snippet below before your website’s closing <span>
                            &lt; /head&gt; </span> tag. Once installed, Hypertarget will automatically
                          start receiving data. </p>
                        <div className="code-editor-wrapper block animate__animated animate__fadeInUp">
                          <div className="code-header">
                            <p>HTML</p>
                          </div>
                          <div className="code-body">
                            <textarea readOnly defaultValue={"<sript>\n\n</sript>"} />
                          </div>
                        </div>
                        <a href className="plan-cta animate__animated animate__animated animate__flipInX">Email Code instructions</a>
                        <div className="d-flex justify-content-end">
                          <a href className="cta animate__animated animate__animated animate__flipInXp">Test Connection</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </form>
    </div>
  )
}
