import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="main-nav landing-nav">
        <div className="nav-wrapper">
          <div className="d-flex">
            <img src="assets/images/menu-bar.svg" className="menu-bar" alt="" />
            <div className="logo-wrapper">
              <img src="assets/images/logo.svg" alt="" />
            </div>
          </div>
          <ul className="nav-list">
            <li><a href>About</a></li>
            <li><a href>Features</a></li>
            <li><a href>Pricing</a></li>
            <li><a href>Testimonials</a></li>
            <li><a href>Help</a></li>
          </ul>
          <ul className="nav-btns">
            <li><a href className="cta-secondary">Sign In</a></li>
            <li><a href className="cta-primary">Sign Up</a></li>
          </ul>
        </div>
        <div className="mobile-nav">
          <div className="menu-header">
            <div className="logo-wrapper">
              <img src="assets/images/logo.svg" alt="" />
            </div>
            <div className="close">
              <img src="assets/images/menu-close.svg" alt="" />
            </div>
          </div>
          <ul className="nav-list">
            <li><a href>About</a></li>
            <li><a href>Features</a></li>
            <li><a href>Pricing</a></li>
            <li><a href>Testimonials</a></li>
            <li><a href>Help</a></li>
          </ul>
        </div>
      </nav>
      <section className="planpage-sec bg-bluegradient pt-60 pb-60">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-12 col-md-8 col-lg-8 col-sm-12 text-center">
              <h3 className="sec-head white-color mb-20">
                Pricing
              </h3>
              <p className="journey-para white-color">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                et dolore magna aliqua. Amet mauris commodo quis imperdiet massa.
              </p>
            </div>
          </div>
          <div className="row">
            <div className="col-12">
              {/* plan page tabs */}
              <ul className="nav nav-tabs price-tabs" id="myTab" role="tablist">
                <li className="nav-item" role="presentation">
                  <a className="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">monthly</a>
                </li>
                <li className="nav-item" role="presentation">
                  <a className="nav-link" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">yearly</a>
                </li>
              </ul>
              <div className="tab-content" id="myTabContent">
                <div className="tab-pane fade show active pt-100" id="home" role="tabpanel" aria-labelledby="home-tab">
                  <div className="row">
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="price-card">
                        <div className="price-header">
                          <p className="price-cat">
                            Basic
                          </p>
                          <h4 className="main-price">
                            $99/mo
                          </h4>
                          <p className="para">
                            Marketing analytics and website flow optimization.
                          </p>
                        </div>
                        <div className="price-body">
                          <h5 className="head">
                            What’s included
                          </h5>
                          <ul className="price-inc-list">
                            <li>6-Month Data History</li>
                            <li>100% support</li>
                            <li>Custom Reports</li>
                            <li>Funnel Optimization</li>
                          </ul>
                          <button className="add-btn">
                            add to cart
                          </button>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="price-card scale-up">
                        <div className="price-header">
                          <p className="price-cat">
                            Pro
                          </p>
                          <h4 className="main-price">
                            $150/mo
                          </h4>
                          <p className="para">
                            Deep marketing channel analysis, website optimization, and smart audiences for growing websites.
                          </p>
                        </div>
                        <div className="price-body">
                          <h5 className="head">
                            Everything in basic +
                          </h5>
                          <ul className="price-inc-list">
                            <li>1 Year Data History</li>
                            <li>Journey Analysis</li>
                            <li>1:1 Onboarding</li>
                            <li>Export Unlimited Smart Audiences</li>
                          </ul>
                          <button className="add-btn">
                            add to cart
                          </button>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="price-card custom">
                        <div className="price-header">
                          <p className="price-cat">
                            Custom
                          </p>
                          <button className="bordered">
                            get in touch 
                            <svg width={22} height={15} viewBox="0 0 22 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M13.8913 1L20.5 7.5M13.8913 14L20.5 7.5M20.5 7.5H1.5" stroke="#192B43" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </button>
                          <p className="para">
                            Higher plans are better served by contacting Hypertarget.
                          </p>
                        </div>
                        <div className="price-body">
                          <h5 className="head">
                            Everything in Pro +
                          </h5>
                          <ul className="price-inc-list">
                            <li>2 Years Data History</li>
                            <li>Budget Planning</li>
                            <li>Advanced User Management</li>
                            <li>Analytics Bootcamp</li>
                            <li>Export Unlimited Events to Facebook, Google Ads &amp; More</li>
                          </ul>
                          <div className="d-flex justify-content-center">
                            <button className="bordered style-2">
                              get in touch 
                              <svg width={22} height={15} viewBox="0 0 22 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M13.8913 1L20.5 7.5M13.8913 14L20.5 7.5M20.5 7.5H1.5" stroke="#192B43" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
                              </svg>
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">2</div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer className="main-footer">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-4 col-md-4 col-sm-12 col-12">
              <img className="ft-logo" src="assets/images/logo.svg" alt="" />
              <p className="para mt-20">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
              </p>
              <ul className="social-links">
                <li><a href><i className="fab fa-facebook" /></a></li>
                <li><a href><i className="fab fa-twitter" /></a></li>
                <li><a href><i className="fab fa-instagram" /></a></li>
              </ul>
              <p className="copy-text">
                ©2021 HYPERTARGET
              </p>
            </div>
            <div className="col-lg-2 offset-lg-1 offset-md-1 col-md-2 col-sm-4 col-12">
              <h4 className="ft-head">
                Product
              </h4>
              <ul className="ft-links">
                <li><a href>Download</a></li>
                <li><a href>Pricing</a></li>
                <li><a href>Locations</a></li>
                <li><a href>Server</a></li>
                <li><a href>Countries</a></li>
                <li><a href>Blog</a></li>
              </ul>
            </div>
            <div className="col-lg-2 col-md-2 col-sm-4 col-12">
              <h4 className="ft-head">
                Feature
              </h4>
              <ul className="ft-links">
                <li><a href>Menu 1</a></li>
                <li><a href>Menu 1</a></li>
                <li><a href>Menu 1</a></li>
                <li><a href>Menu 1</a></li>
                <li><a href>Menu 1</a></li>
                <li><a href>Menu 1</a></li>
              </ul>
            </div>
            <div className="col-lg-2 col-md-2 col-sm-4 col-12">
              <h4 className="ft-head">
                Earn Money
              </h4>
              <ul className="ft-links">
                <li><a href>Affiliate</a></li>
                <li><a href>Become Partner</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
